# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'logon.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_logon(object):
    def setupUi(self, logon):
        logon.setObjectName("logon")
        logon.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(logon)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(logon)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(logon)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(logon)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(logon)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(logon)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(logon)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(logon)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(logon)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 3, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(logon)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 4, 0, 1, 2)

        self.retranslateUi(logon)
        QtCore.QMetaObject.connectSlotsByName(logon)

    def retranslateUi(self, logon):
        _translate = QtCore.QCoreApplication.translate
        logon.setWindowTitle(_translate("logon", "Dialog"))
        self.label.setText(_translate("logon", "学号       "))
        self.label_4.setText(_translate("logon", "姓名"))
        self.label_2.setText(_translate("logon", "密码      "))
        self.label_3.setText(_translate("logon", "再次确定密码"))
        self.pushButton.setText(_translate("logon", "注册"))
